### ISSUE TITLE
Invalid Protobuffer files

### ISSUE THREAD

**Issue by linuxluigi** [SchwarzIT/go-template#117] opened 2022-05-11 06:37 UTC
### What happened?

When creating a new project with a `-` in the name like `test-gt` and enable gRPC. The generated protobuffer package name and the example service will contain also the `-` but this is invalid for protobuffer.

### How can we reproduce this?

Create a new project which contains a `-` in the name like `test-gt`.

### gt version

```bash
0.4.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brumhard** [comment] 2022-05-13 12:31
Closing as duplicate of #97

**Closed by brumhard** 2022-05-13 12:31 UTC
Labels: bug
